### ISSUE TITLE
League client doesn't connect after a match

### ISSUE THREAD

**Issue by o-hauck** [molenzwiebel/Deceive#122]
I am not 100% sure if this is a deceive problem, but I didn't experience it a single time without deceive active. The problem is that sometimes when a match ends and I go back to the client for the results it keeps loading and the only way to stop it is to restart the client.

I'm also not 100% sure but I think it happens when I alt tab from the game before the client refreshes and is going for the end results.

**Comment by mathfalcon** [comment]
Mhm... I have faced the same issue but only when doing ALT+F4 while the nexus is exploding, otherwise it works as expected, maybe a riot client problem?

**Comment by molenzwiebel** [comment]
Neither of these should be caused by Deceive, since it only modifies your chat connection (whereas post-game results are an entirely different service). It likely is some classic case of spaghetti code.

Feel free to prove me wrong if you can find some way to consistently trigger your issue (with Deceive running) and I'll take a look.
