### ISSUE TITLE
Deceive Quarantined by Antivirus

### ISSUE THREAD

**Issue by hahanicee** [molenzwiebel/Deceive#142]
As title states, I opened up Deceive today, like I do any other, and was met with what I thought was a crash. I sat there annoyed for a second, then was surprised by my antivirus software telling me it had quarantined this software that I had been using almost every day prior with no issue.

Now, I am not here to say that there is any sort of malicious activity going on here. I'm not saying this is the fault of the developer or the antivirus software. What I am saying is that there is an issue. I'm not sure how you will fix it, or when, but I am willing to wait however long it takes. I have been a loyal user of this software for the last several years. I've seen it through thick and thin. I know this is something that can be beaten, it can be overcome.

I am looking forward to your next update. Keep up the great work.

Sincerely,
hahanice

**Comment by jf-tobias** [comment]
I just started using Deceive. Happened to me too. I used anti-virus: AVG (Free)

**Comment by molenzwiebel** [comment]
For those encountering this in the future, know that Deceive does not contain viruses (obviously). Virus scanners use heuristics to scan for malware, and sometimes code used in Deceive is also used in malware (for example, Deceive has to look at running processes to find the Riot Client). If an antivirus flags Deceive, please let me know through a comment here or a message in the Discord so that I can submit it for manual verification.

**Comment by cherishomi** [comment]
Ran into this issue twice now with Avast Antivirus. It seems oddly aggressive tonight and has quarantined both the new version v1.12.0 and the old version I was using (v1.10.0). A few months ago it quarantined v1.11.0 and I went back to using the old version. I've made an exception for the latest version now so I should be ok but wanted to leave this comment. It's named the threat as an IDP.Generic
