### ISSUE TITLE
Run into this error when launching Deceive

### ISSUE THREAD

**Issue by Teedann1** [molenzwiebel/Deceive#164]
![Screenshot (168)](https://user-images.githubusercontent.com/117588907/200182355-5ebb79b3-6ae5-4226-a4ff-ce3367bd192c.png)

**Comment by TheAnton205** [comment]
Same issue on my end.

**Comment by danblock97** [comment]
Same issue for me, I assume from @Stabmeqt comment, it still works (appearing offline) just go to close the error

**Comment by molenzwiebel** [comment]
The root cause for this has supposedly been fixed at Riot's end, requiring no Deceive update. @Teedann1 @Stabmeqt @TheAnton205 @danblock97: Could you check whether you still have the issue?

@deranderson I suspect you were suffering from a different issue, as this issue was also showing up for people that had their firewall disabled entirely. But yes, for anyone that stumbles upon this issue later, the first thing you should try is disabling your firewall and/or antivirus. If that fixes it, you'll need to whitelist Deceive in those applications to prevent it from getting blocked.

**Comment by LaLNaoSabeUsar** [comment]
i still have this issue.

**Comment by Stabmeqt** [comment]
@molenzwiebel yeah, still getting this issue while Avast shields are enabled. Made a screenshot for you right now just to confirm
![image](https://user-images.githubusercontent.com/4425552/202250570-99c6e3da-8ef5-45c2-b361-2c463c84dca8.png)

But the core functionality is working (hiding you from a friend list).
![image](https://user-images.githubusercontent.com/4425552/202250715-fbc9ea5c-ddbe-4736-b709-fd5c0a68b351.png)

So I'd say that's not the highest priority issue (still annoying though). Thanks for amazing work!

**Comment by Teedann1** [comment]
> 

It's resolved on my end. Thanks!
