### ISSUE TITLE
Offline Status not working correctly

### ISSUE THREAD

**Issue by SHRoberts91** [molenzwiebel/Deceive#18]
`Deceive Version: 1.5`
`LoL Version: 9.20.292.8264`
Hi, love the app, unfortunately V1.5 seems to have stopped working correctly, not sure if it's the latest patch of league(V9.20) or of Deceive. My Status will show offline and grayed out, but when I start to create a game the status text will update. Once I jump in Queue not only does the status text update but the color goes blue, then when I'm in champ select the color shows green, and in game it's green. Wasn't sure if that's just what I'm seeing, but when I was in game I asked one of my friend and he said I showed up online and in game. I then looked at Deceive in my icon tray and it said it was enabled and should have been showing me as offline.

Along with that issue then I have a question, if it's working correctly should I expect it to still update my status text but stay grey, or is it supposed to still change colors and text on my client, but just always show offline to other people's client?

Thanks again putting time into this!

**Comment by aPinat** [comment]
Hey!

I have written most of the new code in v1.5.0, so I'll try to answer this.
So, I've just downloaded and tested the build molen released and it works fine for me on the same LeagueClient version as you have tried, or at least as expected. 
Now what is expected? If enabled it should always show you as offline (or mobile automatically if you have the mobile app; you can't just force it to be offline anymore if you do have the app) to the friends in your friends list. It should not show the status text or a different color to others. 
However, on your own client you will see the status text updated, when creating a lobby or even the color change to blue once in queue, champ select, in game or spectating etc. This is something that is being forced by the LeagueClient and we can't really modify this that easily. But again, this all should now show on your friends' client is Deceive is working correctly.

Now since it didn't quite work for you that way, I'm going to try to guess what might have happened. Did any client, either RiotClient or LeagueClient, maybe update and patch itself and then relaunch automatically after you started it through Deceive? This would cause the client to "forget" the launch argument Deceive sets to be able to mask your status and would cause your client to start normally without Deceive again. Even though in this case Deceive is then supposed to just exit and not show the tray icon, but maybe it just bugged out here.

In any case, could you just try it again and see whether it works this time and report back any issues? 
Thanks
- aPinat

**Comment by MythixDino** [comment]
League v9.23.298.3143

Since I'm having issues with the same subject I'll just answer here.
It does work for me when I start the client, I'm offline.
However after I've played 1 game my status is online again. When I disable and re-enable deceive it goes offline though, however this is not ideal and I don't know when it stops working either. Could be at the start of the game or at the end.

**Comment by aPinat** [comment]
What the client shows to you is not always correct, it still works for others even if it shows "In Game" or "In Queue" for you. This is something that can't be changed on the client directly. Again, Deceive still does mask the whole status for others.
You can also try using my (unofficial) in development version, here: https://github.com/aPinat/Deceive/releases/latest
It includes fixes for that issue and some others, and should show as offline to you locally as long as it's not one of the blue statuses. But, yeah what the client shows to you is only 'cosmetic', you can only really check whether it's working by looking at a friends client or the League+ app.

**Comment by MythixDino** [comment]
I used that, it seems to be fine now after I played some games. Though I have another minor issue:
[https://content.screencast.com/users/MythixRuby/folders/Default/media/fd3319f9-6f63-44b3-88aa-54f53f449c46/11.20.2019-22.26.png](image)
That happens when the match is over, I don't see anyone leaving the chat and every player is already grayed out (left).

**Comment by aPinat** [comment]
I think this is just League servers (if you're on EUW) dying atm. Nothing is really working right now...

**Comment by molenzwiebel** [comment]
Please let me know if this is still an issue with [v1.5.1](https://github.com/molenzwiebel/Deceive/releases/tag/v1.5.1).
