### ISSUE TITLE
Pull Request / want to contribute

### ISSUE THREAD

**Issue by huachristina** [molenzwiebel/Deceive#214]
Hi! Me and my partner were working have seen this project and were really interested in contributing a bit of our code to this one. We noticed a lot of the issues and worked on them for one of our classes in University, and would love to provide our insights and code if you would like!

**Comment by MedievalSp** [comment]
It is a good idea to look for approval from the owner, but the magic of opensource is that you can fork this project.

Deceive is pretty much broken since the enforcement of Riot Vanguard. For us lonley souls, this tool is unvaluable to play the game without having to worry about people inviting you or seeing you are playing.

I did fork this project in the past to workaround certain limitations, the code is very clean and well documented, but as for now, I don't see any alternative to work around the Vanguard. =(

Cheers!

**Comment by molenzwiebel** [comment]
Please avoid spreading misinformation. Deceive has worked fine with Vanguard on VALORANT for years, and continues to work for League of Legends too. If you are having issues, you should be reporting them on the Discord or as an issue here, not whatever this is.

@huachristina This issue is a case of [Don't Ask to Ask](https://dontasktoask.com/). If you've already done the work, and feel part or all of it is in a state where it could be contributed back, feel free to make a pull request. No promises on how much of it I'd accept (Deceive works fine and I'm hesistant to touch it as long as it stays that way), but I'll always be open to people wanting to contribute to open source.

I'll close this issue now, since it isn't really an issue.
