### ISSUE TITLE
v1.5.0 not working after joining a game

### ISSUE THREAD

**Issue by Stapsous** [molenzwiebel/Deceive#22]
Hi, when I start the client via Deceive my status is offline but whenever I join a game I become Online, then In Game. I confirmed it using an other account on an other PC. Any idea ?

**Comment by aPinat** [comment]
Hey, are you sure it did really work (show you as offline for others) before you joined a game?

Only thing I can think of right now, is that maybe your Riot Client patched after opening Deceive?
That would override Deceive's launch flags and start a League Client without Deceive enabled. But in that case it should not work at first too, so I'm not quite sure...

Could you try to verify again that it does show you as offline for others and later not?
(Also note that, what you see yourself in the client might be incorrect, but you should still be offline to others; but you said you tested on another account, so that is not supposed to happen)

**Comment by adrian675** [comment]
Ok, made an account here just to comment. So after finishing a game, deceive doesn't work anymore i have to change the status to mobile then back to offline to make it work.

**Comment by aPinat** [comment]
@adrian675 That is most likely just the visuals in the client. What is shown to you in client is not always correct, it should still show you as offline to others.
Otherwise you can try this version: https://github.com/aPinat/Deceive/releases/latest
It includes fixes for that issue.

**Comment by molenzwiebel** [comment]
Please let me know if this is still an issue with [v1.5.1](https://github.com/molenzwiebel/Deceive/releases/tag/v1.5.1).
