### ISSUE TITLE
9.24 NA -- Not working in game (Shows status properly instead of offline)

### ISSUE THREAD

**Issue by AnandMaha** [molenzwiebel/Deceive#34]
Noticed when my friend messaged me during a game I was playing. After testing, it seems that everything works fine in the client, but when I enter champ select or a game my status simply becomes the way it's supposed to be... (Also am using 1.61)

**Comment by aPinat** [comment]
I suppose you're on playing on NA? We are seeing multiple reports for Deceive not functioning correctly on NA, and it might have to do with the change to the new chat system in 9.24.

**Comment by aPinat** [comment]
I've had a deeper look into this and Deceive is supposed to be working just fine on NA as well.. Did your Riot Client have to patch or restart after starting with Deceive?
Otherwise something to always keep in mind is that what client shows to you **locally** is not always accurate, especially when it's one of the blue statuses (like Champ Select as you mentioned). Your status is supposed to be **always** offline to others, disregarding what the client shows to you. 
Could you try launching with Deceive again and have your friend check whether "In Queue" etc shows up and report back?
Thanks!

**Comment by AnandMaha** [comment]
1) My client didn’t have to patch after I launched Deceive.

2) I have an alt account that has main account added as a friend. I have both clients open on two laptops, my alt opened normally and my main opened with Deceive. On the alt’s client side, the main acc appears offline (good). But when I queue on my main, the alt acc sees my main acc pop up “In queue”. Same thing occurs when the main acc is in game too; the alt sees that the main is in game. So that’s the issue I’m facing.

**Comment by aPinat** [comment]
Thanks! We have found the issue and I'm working on getting the fix out.

**Comment by aPinat** [comment]
Should be fixed in #35 or https://github.com/aPinat/Deceive/releases/tag/20191216.1.

**Comment by AnandMaha** [comment]
Thanks so much for your work! Everything works now!
