### ISSUE TITLE
Error: Chat disconnected when in Valorant

### ISSUE THREAD

**Issue by Alfredo-Ruiz** [molenzwiebel/Deceive#58]
When I launch the game using Deceive I get an error: chat disconnected in the bottom left and 'service unavailable' where my friends list should be. I tried aPinat's latest release and this issue was fixed but I could not message or invite people to games.
![Valorant](https://user-images.githubusercontent.com/17517738/81502816-2fc12600-92d8-11ea-957f-4b0f689daaa0.png)
Any help with this issue would be appreciated.

**Comment by Alfredo-Ruiz** [comment]
This is the error I get when messaging people with version 1.8.1
![Valorant2](https://user-images.githubusercontent.com/17517738/81503197-33ee4300-92da-11ea-8c69-66eabc93d7fa.png)

**Comment by aPinat** [comment]
Did I understand correctly that with the latest build on my page you can see your friends list again and are connected to lobby chat?
If yes, you should also be able to invite people since that is unrelated to the chat service and is handled by a different server.
As for the "player unreachable" thing, not sure how that happens, but it also seams to happen without Deceive, for example molen can never message me through VALORANT for some reason... Maybe also has something to do with running LeagueClient and VALORANT at the same time maybe...

**Comment by Alfredo-Ruiz** [comment]
Hi aPinat, thanks for the quick reply! That's right - your newest build solves the friends list issue, but even though I can invite people, they are unable to accept the invite, while I have no issues when deceive isn't running. I can also request to join their party but they have no way of accepting.

The message that I've invited them shows up in the chat but there's no option to accept, is that working as intended or am I supposed to be able to join lobbies?
![Untitled 12039](https://user-images.githubusercontent.com/17517738/81577211-133cf080-93a1-11ea-86b0-4f46e7d2c80b.png)

**Comment by aPinat** [comment]
Ah yes, that's right, since they can't see you as online in their friends list, they can't see your lobby and thus can't right click to accept the invite or request to join. 
The only way for the Deceive user to join another lobby currently would be to join an open lobby.

**Comment by Alfredo-Ruiz** [comment]
That makes sense thanks! The toggle idea seems to work perfectly, thanks for your help!
