### ISSUE TITLE
Valorant- Chat Service is Unavailable 

### ISSUE THREAD

**Issue by chibiirina** [molenzwiebel/Deceive#67]
Hi! 

When I use deceive it works since I'm offline but it disconnects my chat service and says the social service is unavailable so I can't see my friends list. From my understanding I'm supposed to still be able to see it and chat with people? Let me know if I misunderstood. 

I'd like to be able to invite specific friends if they are on so seeing it would be useful, but more importantly I can't chat to team/party anymore and can only use voice comms. 

![unknown](https://user-images.githubusercontent.com/67254708/85251197-ebb45b80-b415-11ea-9e4e-3ceddef5740e.png)

Any help is appreciated, thank you!!

**Comment by aPinat** [comment]
Hey, try: https://github.com/aPinat/Deceive/releases
But keep in mind, that for friends to accept your invitation they need to see you as online, as otherwise they can't click to join your party. Best way to do it would be to join an open party (again this can't be a Deceive user), or to disable Deceive shortly.

**Comment by molenzwiebel** [comment]
Please let me know if this is still an issue with v1.10.0.

**Comment by Karlozo** [comment]
I have the same problem as her and doesnt know hot to fix do u have any ide

**Comment by ErisMP4** [comment]
I've also been having the same problem with no fix so far.

**Comment by notsvens** [comment]
update with fix if possible please

**Comment by Karlozo** [comment]
plz help us
