### ISSUE TITLE
Deceive fails to update status to away if switching 'Status Type' to online

### ISSUE THREAD

**Issue by Frontear** [molenzwiebel/Deceive#80]
League has 2 specific status types that are configurable by the end-user. The first is being shown as online, whereas the second is being shown as away.

Normally, if Deceive is disabled in the settings, you can easily toggle between Online and Away simply by pressing the green circle underneath your character profile. Initially you'd expect this to also occur if you simply switch your Status Type in Deceive to Online, then try to toggle, but it does not do such.

I propose that either Deceive add a new Status Type called Away, or Deceive somehow respect the setting applied by the client.

**Comment by aPinat** [comment]
>Initially you'd expect this to also occur if you simply switch your Status Type in Deceive to Online, then try to toggle, but it does not do such.

No, the point of adding the "Online" option was to have Deceive change any Away status to online, so that the user would always be shown as online, even if the client auto-switches to Away after not interacting with it.

> I propose that either Deceive add a new Status Type called Away, or Deceive somehow respect the setting applied by the client.

If you don't want Deceive to change your status, you simply disable it and as you noticed, you can then again toggle it normally.
Adding another option makes no sense, as the "disable" option already does the exact same thing and is less confusing.
