### ISSUE TITLE
Status Type Offline still shows up as League+

### ISSUE THREAD

**Issue by Frontear** [molenzwiebel/Deceive#81]
Effectively the title, if Deceive is set to show status as offline, in the friend list it will still show as League+. This is not the expected behaviour, given that there is a separate status for Mobile/League+

**Comment by aPinat** [comment]
Yes, we are aware of this, and this has worked in the past, but Riot changed their chat system at some point and users that have League+ will be shown as League+ when offline (unless it bugs out) or Deceive telling the server we are offline as the server just sends "Mobile" to other users instead and overwrites what we have sent to it, since it knows you are a League+ user.

The point of still having the option is, that is it possible for non-League+ users to get the Mobile/League+ status. But again, it is not possible the other way around and typically not what you want anyways and handy for the typical user, as it sort of leaks your status, if you are suddenly "Offline" despite always showing as "League+" when really offline.
