### ISSUE TITLE
Deceive not working anymore after new riot update

### ISSUE THREAD

**Issue by zelgawis2** [molenzwiebel/Deceive#85]
Riot updated something on thier side and it looks like the tool is not working anymore. Can u take a look and maybe update Deceive?

**Comment by xCrimin4L** [comment]
Can also vouch for this, seems to be a problem when opening and running the client.

**Comment by molenzwiebel** [comment]
Will take a look, but it might be caused by the League servers being on fire the last few days

**Comment by reyhansofian** [comment]
:+1: this. also happen on Valorant

**Comment by renegade340** [comment]
Yesterday, EU time around about until 1:30 AM today, I used Deceive without any issues. Today it seems to have stopped working properly indeed - just dropping this here. if I start it up the client does start but the chat service is crashing down and deceive is not interacting with it.

**Comment by david19au** [comment]
I couldn't even get into my client - it only turned on the game patcher with an error message saying "Can't connect to Riot servers" or something around these lines. Been having this issue since the past week with both Valorant and League.

**Comment by VitorMaichberger** [comment]
Tool is still working fine for me! Only problem is that it shows I'm online for me.

To reproduce make sure it works I logged on League+ on my second account and I can see I'm showing as offline!

![image](https://user-images.githubusercontent.com/22524486/106277203-757f9f00-6217-11eb-9d74-27c03fe47892.png)

![image](https://user-images.githubusercontent.com/22524486/106277275-90eaaa00-6217-11eb-9e24-6b7c01ac21a6.png)

**Comment by david19au** [comment]
> Tool is still working fine for me! Only problem is that it shows I'm online for me.
> 
> To make sure it works, I logged on League+ on my second account and I can see I'm showing as offline!
> 
> ![image](https://user-images.githubusercontent.com/22524486/106277203-757f9f00-6217-11eb-9d74-27c03fe47892.png)
> 
> ![image](https://user-images.githubusercontent.com/22524486/106277275-90eaaa00-6217-11eb-9e24-6b7c01ac21a6.png)

This is how Deceive works by design, the status will show you're online but as long as you see "Deceive Active!" it will show whatever you set it to appear. The problem that we are facing is that we can't use the tool at all. Yours seem to work fine.

**Comment by molenzwiebel** [comment]
Hey guys, neither me nor @aPinat are able to reproduce this issue so we may need some more information.

Could you please let us know the following:
- Does it consistently not work, or only occasionally? (also try starting League/VALORANT/w/e normally and letting it update completely)
- What game are you trying to launch (League, VALORANT, LoR)?
- What region are you in?
- Do you have some "unconventional" network setup, such as a VPN, Pi-Hole, corporate/school network, etc?

Thanks!

**Comment by david19au** [comment]
Hey, 
for me the issue is occasional, sometimes after launching Deceive a couple of times fixes the issue and I'm able to log in properly. For me it is an issue in League and Valorant, I don't play LoR so not sure about that one. I'm in EUNE and no, no VPN, no Pi-Hole and it's on my home network.

**Comment by renegade340** [comment]
![Unbenannt](https://user-images.githubusercontent.com/78025633/106384004-1497c880-63c9-11eb-8e3d-4aa4a85a5c40.PNG)
Sometimes it is starting correctly as it should - but in the client it shows me as always being "online"  - I also double checked with League+ via a 2nd account if i would appear offline for others and I did - it is nontheless confusing. 

But several times the program itself thows out error messages like the one in this picture or just a simpler one with a smaller error message like "program could not run properly" or something like that. The game still is starting up with both error messages but the chat section of the client is always crashed and out of order for the time being when the error occurs. Also I had the client check for automatic repair today-  without me initializing it - it did that on itself, I assume that is also being caused by deceive, that the launcher thinks it has to repair itself

**Comment by lynier-e** [comment]
hello I'm new to deceive 
I have used deceive for quite a while now but now deceive has an error saying cant launch the game correctly
