### ISSUE TITLE
Wondering if this can be used for wild rift being emulated on pc?

### ISSUE THREAD

**Issue by iNiles** [molenzwiebel/Deceive#96]
I play on bluestacks, and i'm wondering if i could use it for this. If not is there a way to find my lol chat IP while running wild rift, because it seems to be different than the pc versions.

**Comment by aPinat** [comment]
Not with how Deceive currently works. There would be ways, but I think you'd be better off just blocking the connection. The chat server should be the same as on PC as it is shared across all games. It is long not a singular IP anymore though since it goes though Cloudflare, so you would have to block all going to `*.chat.si.riotgames.com`.
